name: Release workflow
on: [push]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - name: checkot
          uses: actions/checkout@v4.1.1

        - name: node install
          uses: actions/setup-node@v2
          with: 
            node-version: 20
        
        - name: install depsss
          working-directory: chrome-extension
          run: npm install
          
        - name: Build files
          working-directory: chrome-extension
          run: npm run build

        - name: zipps build folder
          working-directory: chrome-extension
          run: zip -r build.zip ./build

        - name: upoads to artifact
          uses: actions/upload-artifact@v4
          with : 
            name: build
            path: chrome-extension/build.zip

  release: 
    needs: build
    runs-on: ubuntu-latest
    steps: 
      - name: Downloading build files from artifact
        uses: actions/download-artifact@v4
        with: 
          name: build

      - name: Create release
        uses: actions/create-release@v1
        id: create-release
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with: 
          tag_name: ${{ github.ref_name }}-${{ github.sha }}
          release_name: Release ${{ github.ref_name }}-${{ github.sha }}
          body: |
              New release
          draft: false
          prerelease: false

      - name: Uploadss build
        uses: actions/upload-release-asset@v1
        env: 
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          upload_url: ${{steps.create-release.outputs.upload_url}}
          asset_path: build.zip
          asset_name: build.zip
          asset_content_type: application/zip
          
    
    
